# Generated by Django 5.1.1 on 2024-11-27 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_system_app', '0002_translation_worddictionary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worddictionary',
            options={},
        ),
        migrations.RenameField(
            model_name='translation',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='worddictionary',
            old_name='english_word',
            new_name='source_word',
        ),
        migrations.RenameField(
            model_name='worddictionary',
            old_name='russian_word',
            new_name='translated_word',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='translated_word_count',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='word_count',
        ),
        migrations.AlterUniqueTogether(
            name='worddictionary',
            unique_together={('source_word', 'translated_word')},
        ),
    ]
