# Generated by Django 5.1.1 on 2024-11-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_system_app', '0003_alter_worddictionary_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_word', models.CharField(max_length=255, unique=True)),
                ('russian_translation', models.CharField(max_length=255)),
                ('pos_tag', models.CharField(max_length=50)),
            ],
        ),
    ]
