# Generated by Django 5.1.1 on 2024-11-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_system_app', '0004_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='english_word',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='russian_translation',
            field=models.CharField(),
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['english_word'], name='search_syst_english_f6c35f_idx'),
        ),
    ]
